#pragma once

#include "svnrev.h"

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define VERSION_MAJOR 3
#define VERSION_MINOR 9
#define VERSION_PATCH 9
#define VERSION_REVISION SVN_REV

#define VERSION_CONFIG 399

#define PRODUCT_VERSION TOSTRING(VERSION_MAJOR) "." TOSTRING(VERSION_MINOR) "." TOSTRING(VERSION_PATCH) "." TOSTRING(VERSION_REVISION)
#define FILE_VERSION TOSTRING(VERSION_MAJOR) "." TOSTRING(VERSION_MINOR) "." TOSTRING(VERSION_PATCH) "." TOSTRING(VERSION_REVISION)
